account/urls.py
from django.urls import path, include
from django.conf.urls import url
from account import views as account_views
from rest_framework import routers



urlpatterns = [
    
    #url('', include(router.urls)),
    #url('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', account_views.index, name='index'),
    
    #path('profile/', account_views.account_profile, name='account'),
    #path('edit/', account_views.account_edit, name='account_edit'),
    #path('register/', account_views.account_register, name='account_register'),
    
    path('login/', account_views.account_login, name='login'),
    path('logout/', account_views.account_logout, name='logout'),
    #path('logout_then_login/', auth_views.logout_then_login, name='logoutthenlogin'),
    
    #path('password-change/', auth_views.password_change, name='passwordchange'),
    #path('password-change/done/', auth_views.password_change_done, name='password_change_done'),
    
    #path('password-reset/', auth_views.password_reset, name='password_reset'),
    #path('password-reset/done/', auth_views.password_reset_done, name='password_reset_done'),
    #path('password-confirm/(<uidb64>/<token>/', auth_views.password_reset_confirm, name='password_reset_confirm'),
    #path('password-reset/complete/', auth_views.password_reset_complete, name='password_reset_complete')
    
    ]

maxportal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('timeentry/', include('timeentry.urls')),
    
]

timeentry/urls.py
from django.urls import path, include
from django.conf.urls import url
from timeentry import views
from rest_framework import routers

app_name = 'maxportal'

router = routers.DefaultRouter()
router.register('persons', views.PersonViewSet)
router.register('labors', views.LaborViewSet)
router.register('labtrans', views.LabtransViewSet)

urlpatterns = [
    
    
    #url('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url('main', views.main, name='main'),
    url('entryrecords/', views.entryrecords, name='entryrecords'),
    url('api/', include(router.urls)),
    
    ]

account/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User


# Create your models here.
class Person(models.Model):
    personuid = models.IntegerField(primary_key=True)
    personid = models.CharField(max_length=30, unique=True)
    firstname = models.CharField(max_length=30, null=True)
    lastname = models.CharField(max_length=50, null=True)
    
    
    class Meta:
        db_table = 'person'
    
    
    def __unicode__(self):
        return self.personid
    
#class Person_ext(models.Model):
#    ownerid = models.OneToOneField(Person, on_delete=models.CASCADE, primary_key=True)
#    aln1 = models.CharField(max_length=50, null=True)
#    
#    
#    class Meta:
#        db_table = 'person_ext'
#        
#    def __unicode__(self):
#        return self.aln1

class Labor(models.Model):
    
    laborid = models.IntegerField(primary_key=True)
    laborcode = models.CharField(max_length=8, unique=True)
    status = models.CharField(max_length=12, null=True)
    portalpwd = models.CharField(max_length=50, null=True)
    personid = models.ForeignKey(Person, on_delete=models.CASCADE, db_column='personid', to_field='personid')
    
    class Meta:
        db_table = 'labor'
        
    def __unicode__(self):
        return self.laborcode
    
















    
    
    
    
    

timeentry/models.py
from django.db import models
from django.conf import settings
from account.models import Person, Labor

# Create your models here.

class Labtrans(models.Model):
    
    labtransid = models.IntegerField(primary_key=True)
    laborcode = models.ForeignKey(Labor, on_delete=models.CASCADE, db_column='laborcode', to_field='laborcode')
    refwo = models.CharField(max_length=10, null=True)
    craft = models.CharField(max_length=8, null=True)
    regularhrs = models.FloatField(null=True)
    enterdate = models.DateField(null=True)
    
    class Meta:
        db_table = 'labtrans'
        
    def __unicode__(self):
        return self.labtransid

account/forms.py
from django import forms
from django.forms import ModelForm
from django.conf import settings
from account.models import Person, Labor

class UserLoginForm(forms.ModelForm):
    
    password = forms.CharField(label='Password', widget=forms.PasswordInput) #(attrs={'class': 'sr-only'}))
    #email = forms.CharField(label='Email Address', widget=forms.EmailField) #(attrs={'class': 'form-control'}))
    
    class Meta:
        
        model = Labor
        fields = ('laborcode',)

account/views.py
from django.shortcuts import render, redirect
from rest_framework import viewsets
from account.forms import UserLoginForm
from account.models import Person, Labor
from django.http.response import HttpResponse
from django.urls.base import reverse
#from .serializers import PersonSerializer, LaborSerializer, LabtransSerializer

# Create your views here.
def index(request):
    
    return render(request, 'index.html') #HttpResponse('This is the index page!!')

def account_register(request):
    
           
    return render(request, 'register.html')

def account_profile(request):
    
    return "I am account Info"

def account_edit(request):
    
    return "I am Account Edit"

def account_login(request):
    
    if request.method == 'POST':
    
        m = Labor.objects.get(laborcode=request.POST['laborcode'])
        #m = authenticate(email=request.POST['email'], password=make_password(request.POST['password']))
    
        #if check_password(request.POST['password'], m.portalpwd):
        if request.POST['password'] == m.portalpwd:
            request.session['laborcode'] = m.laborcode
            request.session['is_login'] = True
        
            #return vars(m)
            #return HttpResponse(vars(m))
            #memberdata = {'username': m.username, 'email': m.email}
            #return render(request, 'account_profile.html', {'memberdata': memberdata})
            return redirect(reverse('index'))
    
        else:
        
            return HttpResponse('Your email or password is not correct!')
    

    else:
        
        user_form = UserLoginForm()
        
    return render(request, 'login.html', {'loginform': user_form})   

def account_logout(request):
    
    try:
        
        del request.session['member_id']
        
    except KeyError:
        
        pass
    
    return HttpResponse('You are logged out!')    

timeentry/views.py
from django.shortcuts import render
from rest_framework import viewsets, filters, generics
from timeentry.models import Labtrans
from account.models import Person, Labor
from timeentry.serializers import PersonSerializer, LaborSerializer, LabtransSerializer
from timeentry import urls

# Create your views here.

class PersonViewSet(viewsets.ModelViewSet):
    
    queryset = Person.objects.all()
    serializer_class = PersonSerializer
    
class LaborViewSet(viewsets.ModelViewSet):
    
    queryset = Labor.objects.all()
    serializer_class = LaborSerializer
    filter_fields = ('laborcode',)
    
class LabtransViewSet(viewsets.ModelViewSet):
    
    queryset = Labtrans.objects.all()
    serializer_class = LabtransSerializer
    filter_fields = ('laborcode', 'labtransid',)
    ordering_fields = '__all__'
    
    '''
    def get_queryset(self):
        queryset = Labtrans.objects.all()
        slaborcode = self.request_query_param.get('laborcode', None)
        if slaborcode is not None:
            queryset = queryset.filter(laborcode = slaborcode)
        return queryset
    '''
    
def main(request):
    
    return render(request, 'main.html')

def entryrecords(request):
    
    return render(request, 'entryrecords.html')

account/templates/account_profile.html
{% extends "includes/account_base.html" %}
{% block title %} User Profile {% endblock %}
{% block content %}
	
		
		<div class="container">
		
			{% if loginform.errors %}
			
				<p id="erroralarm">
				
					Please correct the error {{loginform.errors|pluralize}} below!
				
				</p>
			
			{% endif %}
			
			<div>
				Username: {{memberdata.username}}
				</br>
				Email: {{memberdata.email}}
			</div>
		
		</div>
		
		<div id="protocoldiv" style="display:none"></div>
		<div id="logoimg" ></div>
	
	
{% endblock %}

account/templates/includes/account_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}Account Profile{% endblock %}</title>
<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
<link href="{% static "css/signin.css" %}" rel="stylesheet">
</head>

<body>
	<div id="header">
        <nav class="navbar navbar-default">
        	<div class="container-fluid">
        		<div class="navbar-header">
        			<a class="navbar-brand" href="#">Site Name</a>
        		</div>
        		<div id="navbar" class="navbar-collapse collapse">
        			<ul class="nav navbar-nav">
        				<li class="active"><a href="#">Home</a>
        				<li><a href="#">About</a></li>
        				<li><a href="#">Contact</a></li>
        				<li class="dropdown">
        					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" arail-haspopup="true" arial-expanded="false">Dropdown<span class="caret"></span></a>
        					<ul class="dropdown-menu">
        						<li><a href="#">Action</a></li>
        						<li><a href="#">Action1</a></li>
        						<li rile="seperator" class="divider"></li>
        						<li class="dropdown-header">Nav Header</li>
        						<li><a href="#">Seperated Link</a></li>
        					</ul>
        				</li>
        			</ul>
        			<ul class="nav navbar-nav navbar-right">
        				<li class="active"><a href="#">Default </a>
        				<li><a href="#">Static Top</a></li>
        			</ul>
        		</div>
        	</div>
        </nav>
        {% if request.user.is_authenticated %}
        <ul class="menu">
            <li {% if section == "blog" %}class="selected"{% endif %}><a href=#>My Blog</a></li>
            <li {% if section == "account" %}class="selected"{% endif %}><a href=#>Account</a></li>
        </ul>
        {% endif %}
        
        <span class="user">
        {% if request.user.is_authenticated %}
            Hello {{ request.user.username }}, <a href=#>Logout</a>
        {% endif %}
        </span>

        
	</div>
    
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">
                    {{ message|safe }}
                    <a href="#" class="close">×</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <script src="{% static "js/jquery-3.2.1.min.js" %}" ></script>
	<script src="{% static "js/bootstrap.min.js" %}" ></script>
    
</body>

</html>

account/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
	
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">
	
	<title>Index Page</title>

	<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
	<link href="{% static "css/cover.css" %}" rel="stylesheet">

</head>

<body>

	<div class="site-wrapper" >
		<div class="site-wrapper-inner" >
			<div class="cover-container" >
				<div class="masthead clearfix" >
					
					<div class="inner" >
						<h3 class="masthead-brand" >Cover</h3>
						<nav>
							<ul class="nav masthead-nav" >
								
								<li class="active" ><a href="#">Home</a></li>
								<li><a href="#">Feature</a></li>
								<li><a href="account/login">Login/Register</a></li>
								<li><a href="#">Contact</a></li>
								
							</ul>
						</nav>
					</div>
					
				</div>	
				<div class="inner cover" >
					<h1 class="cover-heading" >Cover Your Page</h1>
					<p class="lead">Wa hahahaha </p>
					<p class="lead">
						<a class="btn btn-lg btn-default" href="#">Learn More</a>
					</p>
				</div>
				<div class="mastfoot" >
					<div class="inner">
						<p>Company Information</p>
					</div>
				</div>		
			</div>		
		</div>
		
	
	</div>
	
	<script src="{% static "js/jquery-3.2.1.min.js" %}" ></script>
	<script src="{% static "js/bootstrap.min.js" %}" ></script>

</body>

</html>

account/templates/login.html
{% extends "includes/account_base.html" %}
{% block title %} User Login {% endblock %}
{% block content %}
	
		
		<div class="container">
		
			{% if loginform.errors %}
			
				<p id="erroralarm">
				
					Please correct the error {{loginform.errors|pluralize}} below!
				
				</p>
			
			{% endif %}
			
			<form action="" method="post" class="form-signin">
				<h2 class="form-signin-heading">Please sign in</h2>
			
				
				{% for field in loginform %}
				<fieldset class="control-group">
    			<label class="form-signin" for="id_{{ field.name }}">{{ field.label }}</label>
    			<div class="form-signin">
        			{{ field }}
        			<p class="help-text">{{ field.help_text }} </p>
    			</div>
				</fieldset>
				{% endfor %}
				{% csrf_token %}
				<input class="btn btn-lg btn-primary btn-block" type="submit" name="login" value="login">
			
			</form>
		
		</div>
		
		<div id="protocoldiv" style="display:none"></div>
		<div id="logoimg" ></div>
	
	
{% endblock %}

account/templates/register.html
{% extends "account_base.html" %}
{% block title %} User Registration {% endblock %}
{% block content %}
	<div id="container" >
	
		<div id="regform">
		
			{% if regform.errors %}
			
				<p id="erroralarm">
				
					Please correct the error {{regform.errors|pluralize}} below!
				
				</p>
			
			{% endif %}
			
			<form action="" method="post">
			
				<table >
				
					{{regform.as_table}}
					{% csrf_token %}
				
				</table>
				<input type="submit" name="register" value="register">
			
			</form>
		
		</div>
		
		<div id="protocoldiv" style="display:none"></div>
		<div id="logoimg" ></div>
	
	</div>
{% endblock %}

timeentry/templates/entryrecords.html
{% extends "includes/timeentry_base.html" %}
{% block title %} TimeEntry {% endblock %}
{% block content %}
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main" ng-app="myapp" ng-controller="myctl">
	
     <h1 class="page-header">Time Card Entry</h1>

          {% if messages %}
        	<ul class="messages">
            	{% for message in messages %}
                <li class="{{ message.tags }}">
                    {{ message|safe }}
                    <a href="#" class="close">×</a>
                </li>
            	{% endfor %}
        	</ul>
    		{% endif %}
    
    		
    <form class="form-inline">
    	<div class="form-group">
    		<label>Start Date</label>
    		<input type="date" class="form-control" ng-model="startdate">
    	</div>
    	<div class="form-group">
    		<label>End Date</label>
    		<input type="date" class="form-control" ng-model="enddate">
    	</div>
    	<button class="btn btn-default" ng-click="query()">QUERY</button>
    
    </form>    
    {% verbatim %}
    
    	your input: {{period}} <hr>
    	Get result amount: {{count}} <hr>
    	Get error: {{error}} <hr>
    
    {% endverbatim %}  
    
    <h2 class="sub-header"></h2>
	<h2 class="sub-header">Time Entry Records</h2>
	
	<div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>labtransid</th>
                  <th>laborcode</th>
                  <th>enterdate</th>
                  <th>refwo</th>
                  <th>craft</th>
                  <th>regularhrs</th>
                  <th></th>
                </tr>
              </thead>
              {% verbatim %}
              <tbody>
                <tr ng-repeat="x in records">
                  <td>{{x.labtransid}}</td>
                  <td>{{x.laborcode}}</td>
                  <td>{{x.enterdate}}</td>
                  <td>{{x.refwo}}</td>
                  <td>{{x.craft}}</td>
                  <td>{{x.regularhrs}}</td>
                  <td><button class="btn btn-primary btn-xs" ng-click="querydetail()">Detail</button></td>
                </tr>
              </tbody>
              {% endverbatim %} 
            </table>
            
     </div>
</div>
{% endblock %}

timeentry/templates/includes/timeentry_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}Time Card Entry{% endblock %}</title>
<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
<link href="{% static "css/dashboard.css" %}" rel="stylesheet">
</head>

<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">MAXPROTAL</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Settings</a></li>
            <li><a href="#">Profile</a></li>
            <li><a href="#">Help</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
          	
            <li class="active"><a href="{% url 'maxportal:main' %}">Overview</a></li>
            
            <li><a href="{% url 'maxportal:entryrecords' %}">Time Entry</a></li>
            
          </ul>
          <!--
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item</a></li>
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
            <li><a href="">More navigation</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
          </ul>
          -->
        </div>
        {% block content %}
        
    	{% endblock %}
      </div>
    </div>

    <script src="{% static "js/jquery-3.2.1.min.js" %}" ></script>
	<script src="{% static "js/bootstrap.min.js" %}" ></script>
	<script src="{% static "js/angular.min.js" %}" ></script>
	<script src="{% static "js/maxportal.js" %}"></script>
	
    
</body>

</html>

timeentry/templates/main.html
{% extends "includes/timeentry_base.html" %}
{% block title %} Configuration {% endblock %}

{% block content %}
	<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Dashboard</h1>

          <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
          </div>

          <h2 class="sub-header">Section title</h2>
          {% if messages %}
        	<ul class="messages">
            	{% for message in messages %}
                <li class="{{ message.tags }}">
                    {{ message|safe }}
                    <a href="#" class="close">×</a>
                </li>
            	{% endfor %}
        	</ul>
    		{% endif %}
    
    		
          
        </div>
	
	<div id="container" >
	
		TimeEntry Main Page!
	
	</div>
{% endblock %}